// <auto-generated />
using LexiconMVCData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LexiconMVCData.Migrations
{
    [DbContext(typeof(LexiconMVCDbContext))]
    partial class LexiconMVCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LexiconMVCData.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Göteborg",
                            Name = "Adam Adamsson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 2,
                            City = "Malmö",
                            Name = "Bertil Bertilsson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 3,
                            City = "Stockholm",
                            Name = "Carl Carlsson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 4,
                            City = "Göteborg",
                            Name = "Dan Danielsson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 5,
                            City = "Malmö",
                            Name = "Erik Eriksson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 6,
                            City = "Stockholm",
                            Name = "Frans Fransson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 7,
                            City = "Göteborg",
                            Name = "Gustav Gustavsson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 8,
                            City = "Malmö",
                            Name = "Henrik Henriksson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 9,
                            City = "Stockholm",
                            Name = "Ivar Ivarsson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 10,
                            City = "Göteborg",
                            Name = "Jan Jansson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 11,
                            City = "Malmö",
                            Name = "Karl Karlsson",
                            PhoneNumber = "031-123456"
                        },
                        new
                        {
                            Id = 12,
                            City = "Stockholm",
                            Name = "Lars Larsson",
                            PhoneNumber = "031-123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
